### ISSUE TITLE
Missing data files

### ISSUE THREAD

**Issue by Piyushi-0** [thibsej/unbalanced-ot-functionals#1]
Hi,
Could you please upload the files "density_a.png" & "density_b.png" that are used in lines 62, 63 in examples/plot_unb_gradient_flows_2D_frame.py?

Thanks.

**Comment by thibsej** [comment]
Hello,
Sorry for the delay. I have just uploaded the data used in "examples/plot_unb_gradient_flows_2D_frame.py". You should now be able to run the code. If there is any issue, feel free to ask anything. :)
